scrape_configs:
- job_name: supervisor_agent
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 5s
  metrics_path: /metrics/
  scheme: http
  follow_redirects: true
  #enable_http2: true
  static_configs:
  - targets:
    - localhost:8080
    labels:
      env: prod